(define-module (gst)
  #:use-module (gi)
  #:use-module (gi repository)
  #:use-module (system foreign)
  #:use-module (system foreign-library))
(define str "videotestsrc ! autovideosink")
(require "Gst" "1.0")
;;(use-typelibs ("Gst" "1.0"))
(load-by-name "Gst" "parse_launch")
(load-by-name "Gst" "init")
(load-by-name "Gst" "Element")
(load-by-name "Gst" "State")
(load-by-name "Gst" "Bus")
(load-by-name "Gst" "MessageType")
(init!)
(define pp (parse-launch str))
(set-state pp (symbol->state 'playing))
(define bus (get-bus pp))
(define msg (timed-pop-filtered bus 1000000000 (number->message-type 3)))
(display pp) (newline)
(display bus) (newline)
(exit 0)
